import React, { FormEvent, useCallback, useEffect, useState } from 'react';
import './App.css';
import { PublicPath, PublicSite } from './PublicSite';

type Role = 'freelancer' | 'client';
type DashboardScreen = 'overview' | 'payments' | 'wallet' | 'transactions' | 'escrow' | 'settings' | 'outstanding' | 'history' | 'profile';
type PaymentFilter = 'all' | 'active' | 'escrow' | 'completed' | 'disputed' | 'failed' | 'expired';
type PaymentStatus = 'pending' | 'approved' | 'funding_pending' | 'funded' | 'work_submitted' | 'release_pending' | 'released' | 'disputed' | 'failed' | 'expired' | 'cancelled';
type PaymentCurrency = 'USD' | 'EUR' | 'GBP' | 'SSP' | 'UGX' | 'KSH' | 'TSH' | 'SDG';

interface User {
  id: string;
  name: string;
  email: string;
  role: Role;
  walletAddress: string;
  phone?: string;
  pushTokens?: string[];
  complianceStatus?: 'not_started' | 'pending_review' | 'approved' | 'rejected';
  emailVerified: boolean;
}

interface Transaction {
  id: string;
  kind: 'funding' | 'release' | 'refund' | 'send';
  amountBeam: number;
  status: 'pending' | 'confirmed' | 'failed';
  walletTransactionId: string;
  paymentRequestId?: string;
  createdAt?: string;
}

interface PaymentRequest {
  id: string;
  title: string;
  description: string;
  amountBeam: number;
  currency: PaymentCurrency;
  status: PaymentStatus;
  dueDate?: string;
  workNote?: string;
  disputeReason?: string;
  freelancer: User;
  client: User;
  freelancerId: string;
  clientId: string;
  transactions: Transaction[];
  createdAt: string;
}

interface AppNotification {
  id: string;
  title: string;
  message: string;
  read: boolean;
  createdAt: string;
  channels?: Array<'in_app' | 'email' | 'sms' | 'push'>;
}

const statusLabels: Record<PaymentStatus, string> = {
  pending: 'Awaiting approval', approved: 'Ready to fund', funding_pending: 'Funding confirmation',
  funded: 'Escrow funded', work_submitted: 'Work submitted', release_pending: 'Release confirmation',
  released: 'Paid', disputed: 'Disputed', failed: 'Failed', expired: 'Expired', cancelled: 'Cancelled',
};
const paymentCurrencies: PaymentCurrency[] = ['USD', 'EUR', 'GBP', 'SSP', 'UGX', 'KSH', 'TSH', 'SDG'];

function paymentCurrency(payment: PaymentRequest): PaymentCurrency {
  return payment.currency ?? 'USD';
}

function paymentAmount(payment: PaymentRequest): string {
  return `${payment.amountBeam.toLocaleString()} ${paymentCurrency(payment)}`;
}

function paymentLink(payment: PaymentRequest): string {
  return `${window.location.origin}/payment-requests/${payment.id}`;
}

function qrCodeUrl(link: string): string {
  return `https://api.qrserver.com/v1/create-qr-code/?size=156x156&margin=10&data=${encodeURIComponent(link)}`;
}

function notificationChannelLabel(channel: 'in_app' | 'email' | 'sms' | 'push'): string {
  if (channel === 'in_app') return 'in app';
  return channel;
}

function downloadReceipt(payment: PaymentRequest): void {
  const releasedTransaction = payment.transactions.find((transaction) => transaction.kind === 'release' && transaction.status === 'confirmed');
  const receipt = [
    'WorkingBeam Payment Receipt',
    '',
    `Receipt ID: WB-${payment.id.slice(0, 8).toUpperCase()}`,
    `Payment request: ${payment.title}`,
    `Status: ${statusLabels[payment.status]}`,
    `Amount: ${paymentAmount(payment)}`,
    `Freelancer: ${payment.freelancer.name} <${payment.freelancer.email}>`,
    `Client: ${payment.client.name} <${payment.client.email}>`,
    `Created: ${new Date(payment.createdAt).toLocaleString()}`,
    payment.dueDate ? `Due date: ${payment.dueDate}` : 'Due date: Not set',
    releasedTransaction ? `Transaction ID: ${releasedTransaction.walletTransactionId}` : 'Transaction ID: Not confirmed yet',
    `Payment link: ${paymentLink(payment)}`,
    '',
    'Generated by WorkingBeam.',
  ].join('\n');
  const blob = new Blob([receipt], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = `workingbeam-receipt-${payment.id.slice(0, 8)}.txt`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

class ApiError extends Error {
  constructor(message: string, readonly code?: string) { super(message); }
}

async function request<T>(path: string, token?: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(path, {
    ...init,
    headers: {
      ...(init.body ? { 'content-type': 'application/json' } : {}),
      ...(token ? { authorization: `Bearer ${token}` } : {}),
      ...init.headers,
    },
  });
  const payload = response.status === 204 ? {} : await response.json();
  if (!response.ok) throw new ApiError(payload.error ?? 'Request failed', payload.code);
  return payload as T;
}

function AuthScreen({ onAuthenticated, initialRegistering = false }: { onAuthenticated: (user: User, token: string) => void; initialRegistering?: boolean }) {
  const [registering, setRegistering] = useState(initialRegistering);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');
  const [verificationEmail, setVerificationEmail] = useState('');
  const [verificationCode, setVerificationCode] = useState('');
  const [form, setForm] = useState({
    name: '', email: '', password: '', role: 'freelancer' as Role, walletAddress: '', phone: '',
  });

  const submit = async (event: FormEvent) => {
    event.preventDefault(); setError(''); setMessage(''); setLoading(true);
    try {
      if (registering) {
        const result = await request<{ requiresVerification: true; email: string } | { user: User; token: string }>('/api/auth/register', undefined, {
          method: 'POST', body: JSON.stringify(form),
        });
        if ('token' in result) onAuthenticated(result.user, result.token);
        else {
          setVerificationEmail(result.email);
          setMessage(`We sent a six-digit verification code to ${result.email}.`);
        }
      } else {
        const result = await request<{ user: User; token: string }>('/api/auth/login', undefined, {
          method: 'POST', body: JSON.stringify({ email: form.email, password: form.password }),
        });
        onAuthenticated(result.user, result.token);
      }
    } catch (caught) {
      if (caught instanceof ApiError && caught.code === 'EMAIL_UNVERIFIED') {
        setVerificationEmail(form.email.trim().toLowerCase());
        setMessage('Your account is waiting for email verification. Enter the code or request a new one.');
      } else setError(caught instanceof Error ? caught.message : 'Unable to continue');
    } finally { setLoading(false); }
  };

  const verifyEmail = async (event: FormEvent) => {
    event.preventDefault(); setError(''); setLoading(true);
    try {
      const result = await request<{ user: User; token: string }>('/api/auth/verify-email', undefined, {
        method: 'POST', body: JSON.stringify({ email: verificationEmail, code: verificationCode }),
      });
      onAuthenticated(result.user, result.token);
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to verify email'); }
    finally { setLoading(false); }
  };

  const resendCode = async () => {
    setError(''); setMessage('');
    setLoading(true);
    try {
      await request('/api/auth/resend-verification', undefined, {
        method: 'POST', body: JSON.stringify({ email: verificationEmail }),
      });
      setMessage('A new verification code has been sent. It expires in 10 minutes.');
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to resend code'); }
    finally { setLoading(false); }
  };

  return (
    <main className="auth-shell">
      <section className="auth-story">
        <a className="brand light" href="/">Working<span>Beam</span></a>
        <div className="hero-copy">
          <p className="eyebrow">Private freelance payments</p>
          <h1>Work delivered.<br />Payment protected.</h1>
          <p>Request work payments, fund escrow in BEAM, and release funds after delivery—with every step visible to both sides.</p>
        </div>
        <div className="trust-row"><span>Escrow workflow</span><span>Beam privacy</span><span>On-chain confirmation</span></div>
      </section>
      <section className="auth-panel">
        <div className="auth-card">
          {verificationEmail ? <>
            <p className="eyebrow dark">Secure your account</p>
            <h2>Verify your email</h2>
            <p className="muted">Enter the six-digit code sent to <strong>{verificationEmail}</strong>. Codes expire after 10 minutes.</p>
            <form onSubmit={verifyEmail}>
              <label>Verification code<input className="verification-code" required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={verificationCode} onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, '').slice(0, 6))} placeholder="000000" /></label>
              {message && <div className="success-banner">{message}</div>}
              {error && <div className="error-banner">{error}</div>}
              <button className="primary full" disabled={loading || verificationCode.length !== 6}>{loading ? 'Verifying…' : 'Verify and continue'}</button>
              <div className="resend-panel"><span>Need another code?</span><button type="button" className="secondary full" disabled={loading} onClick={() => void resendCode()}>Send a new code</button></div>
            </form>
            <p className="auth-switch"><button onClick={() => { setVerificationEmail(''); setVerificationCode(''); setError(''); setMessage(''); }}>Back to sign in</button></p>
          </> : <>
          <p className="eyebrow dark">{registering ? 'Create your workspace' : 'Welcome back'}</p>
          <h2>{registering ? 'Start with WorkingBeam' : 'Sign in'}</h2>
          <p className="muted">{registering ? 'Your email and Beam receiving token are verified before the account is activated.' : 'Track escrow, delivery, and payment in one secure place.'}</p>
          <form onSubmit={submit}>
            {registering && <label>Full name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Amina Deng" /></label>}
            <label>Email address<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label>
            <label>Password<input required minLength={8} type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="At least 8 characters" /></label>
            {registering && <>
              <div className="role-picker">
                <button type="button" className={form.role === 'freelancer' ? 'selected' : ''} onClick={() => setForm({ ...form, role: 'freelancer' })}><strong>Freelancer</strong><small>Request and receive payments</small></button>
                <button type="button" className={form.role === 'client' ? 'selected' : ''} onClick={() => setForm({ ...form, role: 'client' })}><strong>Client</strong><small>Fund and release escrow</small></button>
              </div>
              <label>Beam wallet address or token<input required minLength={10} value={form.walletAddress} onChange={(e) => setForm({ ...form, walletAddress: e.target.value })} placeholder="Paste a real Beam address or payment token" /><small>Validated securely by the connected Beam Wallet API.</small></label>
              <label>Phone <small>(optional)</small><input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="+211 ..." /></label>
            </>}
            {error && <div className="error-banner">{error}</div>}
            <button className="primary full" disabled={loading}>{loading ? 'Please wait…' : registering ? 'Create account' : 'Sign in'}</button>
          </form>
          <p className="auth-switch">{registering ? 'Already have an account?' : 'New to WorkingBeam?'} <button onClick={() => { setRegistering(!registering); setError(''); }}>{registering ? 'Sign in' : 'Create one'}</button></p>
          </>}
        </div>
      </section>
    </main>
  );
}

function PaymentCard({ payment, user, onAction }: {
  payment: PaymentRequest; user: User; onAction: (action: string, payment: PaymentRequest) => void;
}) {
  const pendingTransaction = payment.transactions.find((transaction) => transaction.status === 'pending');
  const link = paymentLink(payment);
  return (
    <article className="payment-card">
      <div className="payment-top">
        <div><span className={`status ${payment.status}`}>{statusLabels[payment.status]}</span><h3>{payment.title}</h3></div>
        <div className="amount"><strong>{payment.amountBeam.toLocaleString()}</strong><span>{paymentCurrency(payment)}</span></div>
      </div>
      <p className="description">{payment.description || 'No additional description.'}</p>
      {payment.dueDate && <p className={payment.status === 'expired' ? 'due-date overdue' : 'due-date'}>Due {new Date(`${payment.dueDate}T00:00:00`).toLocaleDateString()}</p>}
      <div className="counterparty"><div className="avatar">{(user.role === 'client' ? payment.freelancer.name : payment.client.name).slice(0, 1)}</div><div><small>{user.role === 'client' ? 'Freelancer' : 'Client'}</small><strong>{user.role === 'client' ? payment.freelancer.name : payment.client.name}</strong></div></div>
      <div className="payment-share">
        <div>
          <small>Generated payment link</small>
          <code>{link}</code>
          <div className="share-actions">
            <button className="secondary" aria-label={`Copy payment link for ${payment.title}`} onClick={() => void navigator.clipboard?.writeText(link)}>Copy link</button>
            <a className="secondary link-button" href={link}>Open</a>
          </div>
        </div>
        <img src={qrCodeUrl(link)} alt={`QR code for ${payment.title} payment link`} loading="lazy" />
      </div>
      {payment.workNote && <div className="detail-note"><strong>Delivery</strong><p>{payment.workNote}</p></div>}
      {payment.disputeReason && <div className="detail-note danger"><strong>Dispute</strong><p>{payment.disputeReason}</p></div>}
      {payment.status === 'failed' && <div className="detail-note danger"><strong>Payment failed</strong><p>Review the wallet transaction and create or fund a replacement request when ready.</p></div>}
      {payment.status === 'expired' && <div className="detail-note"><strong>Request expired</strong><p>This request passed its due date before approval or funding.</p></div>}
      <div className="timeline">
        <span className="done">Requested</span><span className={payment.status !== 'pending' ? 'done' : ''}>Approved</span><span className={['funded','work_submitted','release_pending','released'].includes(payment.status) ? 'done' : ''}>Funded</span><span className={['work_submitted','release_pending','released'].includes(payment.status) ? 'done' : ''}>Delivered</span><span className={payment.status === 'released' ? 'done' : ''}>Paid</span>
      </div>
      <div className="card-actions">
        {user.role === 'client' && payment.status === 'pending' && <button className="primary" onClick={() => onAction('approve', payment)}>Approve request</button>}
        {user.role === 'client' && payment.status === 'approved' && <button className="primary" onClick={() => onAction('fund', payment)}>Fund escrow</button>}
        {user.role === 'freelancer' && payment.status === 'funded' && <button className="primary" onClick={() => onAction('submit-work', payment)}>Submit work</button>}
        {user.role === 'client' && payment.status === 'work_submitted' && <button className="primary" onClick={() => onAction('release', payment)}>Release payment</button>}
        {pendingTransaction && <button className="secondary" onClick={() => onAction(`refresh:${pendingTransaction.id}`, payment)}>Check confirmation</button>}
        {payment.status === 'released' && <button className="secondary" onClick={() => downloadReceipt(payment)}>Download receipt</button>}
        {['funded','work_submitted'].includes(payment.status) && <button className="text-danger" onClick={() => onAction('dispute', payment)}>Open dispute</button>}
      </div>
      {payment.transactions.length > 0 && <div className="tx-list">{payment.transactions.map((transaction) => <div key={transaction.id}><span>{transaction.kind}</span><code>{transaction.walletTransactionId.slice(0, 18)}…</code><b className={transaction.status}>{transaction.status}</b></div>)}</div>}
    </article>
  );
}

function Dashboard({ initialUser, token, onLogout, onUserUpdated, initialScreen = 'overview' }: { initialUser: User; token: string; onLogout: () => void; onUserUpdated: (user: User) => void; initialScreen?: DashboardScreen }) {
  const [currentUser, setCurrentUser] = useState(initialUser);
  const [payments, setPayments] = useState<PaymentRequest[]>([]);
  const [walletTransactions, setWalletTransactions] = useState<Transaction[]>([]);
  const [notifications, setNotifications] = useState<AppNotification[]>([]);
  const [showCreate, setShowCreate] = useState(false);
  const [showNotifications, setShowNotifications] = useState(false);
  const [showLogoutConfirm, setShowLogoutConfirm] = useState(false);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState('');
  const [walletMode, setWalletMode] = useState('checking');
  const [emailMode, setEmailMode] = useState('checking');
  const [emailAvailable, setEmailAvailable] = useState(false);
  const [pushMode, setPushMode] = useState('disabled');
  const [pushAvailable, setPushAvailable] = useState(false);
  const [smsMode, setSmsMode] = useState('disabled');
  const [smsAvailable, setSmsAvailable] = useState(false);
  const [screen, setScreen] = useState<DashboardScreen>(initialScreen);
  const [profileEditing, setProfileEditing] = useState(false);
  const [paymentFilter, setPaymentFilter] = useState<PaymentFilter>('all');
  const [form, setForm] = useState({ clientEmail: '', title: '', description: '', amountBeam: '', currency: 'USD' as PaymentCurrency, dueDate: '' });
  const [sendForm, setSendForm] = useState({ address: '', amountBeam: '', note: '' });
  const [profileForm, setProfileForm] = useState({ name: initialUser.name, phone: initialUser.phone ?? '', walletAddress: initialUser.walletAddress });

  const load = useCallback(async () => {
    try {
      const [paymentData, notificationData, health] = await Promise.all([
        request<{ paymentRequests: PaymentRequest[] }>('/api/payment-requests', token),
        request<{ notifications: AppNotification[] }>('/api/notifications', token),
        request<{ wallet: { mode: string }; email: { mode: string; available: boolean }; push?: { mode: string; available: boolean }; sms?: { mode: string; available: boolean } }>('/api/health'),
      ]);
      setPayments(paymentData.paymentRequests); setNotifications(notificationData.notifications); setWalletMode(health.wallet.mode); setEmailMode(health.email.mode); setEmailAvailable(health.email.available); setPushMode(health.push?.mode ?? 'disabled'); setPushAvailable(Boolean(health.push?.available)); setSmsMode(health.sms?.mode ?? 'disabled'); setSmsAvailable(Boolean(health.sms?.available));
      const walletData = await request<{ transactions: Transaction[] }>('/api/wallet/transactions', token);
      setWalletTransactions(walletData.transactions);
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load dashboard'); }
  }, [token]);

  useEffect(() => { void load(); }, [load]);

  const mutate = async (key: string, path: string, body?: object) => {
    setBusy(key); setError('');
    try { await request(path, token, { method: 'POST', body: body ? JSON.stringify(body) : undefined }); await load(); }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'Action failed'); }
    finally { setBusy(''); }
  };

  const act = async (action: string, payment: PaymentRequest) => {
    if (action.startsWith('refresh:')) return mutate(action, `/api/transactions/${action.split(':')[1]}/refresh`);
    if (action === 'submit-work') {
      const workNote = window.prompt('Add a delivery note or link to the completed work:');
      if (workNote) await mutate(`${action}:${payment.id}`, `/api/payment-requests/${payment.id}/submit-work`, { workNote });
      return;
    }
    if (action === 'dispute') {
      const reason = window.prompt('Explain the dispute (at least 10 characters):');
      if (reason) await mutate(`${action}:${payment.id}`, `/api/payment-requests/${payment.id}/dispute`, { reason });
      return;
    }
    await mutate(`${action}:${payment.id}`, `/api/payment-requests/${payment.id}/${action}`);
  };

  const createPayment = async (event: FormEvent) => {
    event.preventDefault(); setBusy('create'); setError('');
    try {
      await request('/api/payment-requests', token, { method: 'POST', body: JSON.stringify({ ...form, amountBeam: Number(form.amountBeam) }) });
      setForm({ clientEmail: '', title: '', description: '', amountBeam: '', currency: 'USD', dueDate: '' }); setShowCreate(false); await load();
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to create request'); }
    finally { setBusy(''); }
  };

  const updateProfile = async (event: FormEvent) => {
    event.preventDefault(); setBusy('profile'); setError('');
    try {
      const result = await request<{ user: User }>('/api/auth/me', token, { method: 'PATCH', body: JSON.stringify(profileForm) });
      setCurrentUser(result.user);
      onUserUpdated(result.user);
      setProfileForm({ name: result.user.name, phone: result.user.phone ?? '', walletAddress: result.user.walletAddress });
      setProfileEditing(false);
      setScreen('profile');
      await load();
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to update profile'); }
    finally { setBusy(''); }
  };

  const generateWallet = async () => {
    setBusy('generate-wallet'); setError('');
    try {
      const result = await request<{ user: User; address: string }>('/api/wallet/generate', token, { method: 'POST' });
      setCurrentUser(result.user); onUserUpdated(result.user);
      setProfileForm({ name: result.user.name, phone: result.user.phone ?? '', walletAddress: result.user.walletAddress });
      await load();
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to generate wallet'); }
    finally { setBusy(''); }
  };

  const sendPayment = async (event: FormEvent) => {
    event.preventDefault(); setBusy('send-payment'); setError('');
    try {
      await request('/api/wallet/send', token, { method: 'POST', body: JSON.stringify({ ...sendForm, amountBeam: Number(sendForm.amountBeam) }) });
      setSendForm({ address: '', amountBeam: '', note: '' });
      await load();
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to send payment'); }
    finally { setBusy(''); }
  };

  const registerPushToken = async () => {
    const tokenValue = window.prompt('Paste the push provider token for this browser/device:');
    if (!tokenValue) return;
    setBusy('push-token'); setError('');
    try {
      const result = await request<{ user: User }>('/api/notifications/push-token', token, { method: 'POST', body: JSON.stringify({ token: tokenValue }) });
      setCurrentUser(result.user); onUserUpdated(result.user);
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to register push token'); }
    finally { setBusy(''); }
  };

  const requestComplianceReview = async () => {
    setBusy('compliance'); setError('');
    try {
      const result = await request<{ user: User }>('/api/compliance/review', token, { method: 'POST' });
      setCurrentUser(result.user); onUserUpdated(result.user);
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to request compliance review'); }
    finally { setBusy(''); }
  };

  const total = payments.reduce((sum, item) => sum + item.amountBeam, 0);
  const secured = payments.filter((item) => ['funded','work_submitted','release_pending'].includes(item.status)).reduce((sum, item) => sum + item.amountBeam, 0);
  const paid = payments.filter((item) => item.status === 'released').reduce((sum, item) => sum + item.amountBeam, 0);
  const currentMonth = new Date().toISOString().slice(0, 7);
  const monthlyRevenue = payments.filter((item) => item.status === 'released' && item.createdAt.slice(0, 7) === currentMonth).reduce((sum, item) => sum + item.amountBeam, 0);
  const activePayments = payments.filter((item) => ['approved','funding_pending','funded','work_submitted','release_pending','disputed'].includes(item.status));
  const activeContracts = new Set(activePayments.map((item) => currentUser.role === 'client' ? item.freelancerId : item.clientId)).size;
  const pendingSpend = payments.filter((item) => ['pending','approved','funding_pending'].includes(item.status)).reduce((sum, item) => sum + item.amountBeam, 0);
  const analyticsLabel = currentUser.role === 'client' ? 'Spending analytics' : 'Pipeline analytics';
  const analyticsHint = currentUser.role === 'client' ? 'Pending approval/funding' : 'Pending client movement';
  const failedPayments = payments.filter((item) => item.status === 'failed').length;
  const expiredPayments = payments.filter((item) => item.status === 'expired').length;
  const unread = notifications.filter((item) => !item.read).length;
  const transactions = walletTransactions.map((transaction) => {
    const payment = transaction.paymentRequestId ? payments.find((item) => item.id === transaction.paymentRequestId) : undefined;
    return { ...transaction, paymentTitle: payment?.title ?? (transaction.kind === 'send' ? 'Direct send' : 'Wallet activity') };
  });
  const confirmedTransactions = transactions.filter((transaction) => transaction.status === 'confirmed');
  const outstandingPayments = payments.filter((payment) => ['pending','approved','funding_pending','funded','work_submitted','release_pending','disputed','failed'].includes(payment.status));
  const historyPayments = payments.filter((payment) => ['released','cancelled','failed','expired'].includes(payment.status) || payment.transactions.length > 0);
  const filteredPayments = payments.filter((payment) => {
    if (paymentFilter === 'active') return !['released', 'disputed', 'failed', 'expired', 'cancelled'].includes(payment.status);
    if (paymentFilter === 'escrow') return ['funding_pending', 'funded', 'work_submitted', 'release_pending'].includes(payment.status);
    if (paymentFilter === 'completed') return payment.status === 'released';
    if (paymentFilter === 'disputed') return payment.status === 'disputed';
    if (paymentFilter === 'failed') return payment.status === 'failed';
    if (paymentFilter === 'expired') return payment.status === 'expired';
    return true;
  });

  const paymentGrid = (items: PaymentRequest[]) => (
    <section className="payments-grid">
      {items.length === 0 ? <div className="empty-state"><div>↗</div><h3>{payments.length === 0 ? 'No payment requests yet' : 'No requests match this filter'}</h3><p>{payments.length === 0 ? (currentUser.role === 'freelancer' ? 'Create your first request after agreeing on work with a client.' : 'Requests sent to your account will appear here.') : 'Try another payment status to see more activity.'}</p>{payments.length === 0 && currentUser.role === 'freelancer' && <button className="primary" onClick={() => setShowCreate(true)}>Create request</button>}</div> : items.map((payment) => <PaymentCard key={payment.id} payment={payment} user={currentUser} onAction={(action, item) => { if (!busy) void act(action, item); }} />)}
    </section>
  );

  return (
    <div className="dashboard-shell">
      <header className="topbar">
        <button className="brand brand-button" onClick={() => setScreen('overview')}>Working<span>Beam</span></button>
        <nav>
          <button className={screen === 'overview' ? 'active' : ''} onClick={() => setScreen('overview')}>Overview</button>
          <button className={screen === 'payments' ? 'active' : ''} onClick={() => setScreen('payments')}>Payments</button>
          {currentUser.role === 'client' && <button className={screen === 'outstanding' ? 'active' : ''} onClick={() => setScreen('outstanding')}>Outstanding</button>}
          {currentUser.role === 'client' && <button className={screen === 'history' ? 'active' : ''} onClick={() => setScreen('history')}>History</button>}
          <button className={screen === 'escrow' ? 'active' : ''} onClick={() => setScreen('escrow')}>Escrow</button>
        </nav>
        <div className="top-actions"><button className={screen === 'wallet' ? 'header-link active' : 'header-link'} onClick={() => setScreen('wallet')}>Wallet</button><button className={screen === 'settings' ? 'header-link active' : 'header-link'} onClick={() => setScreen('settings')}>Settings</button><button className="notification-button" onClick={() => setShowNotifications(!showNotifications)}>!{unread > 0 && <b>{unread}</b>}</button><button className={screen === 'profile' ? 'profile profile-button active' : 'profile profile-button'} onClick={() => setScreen('profile')}><div className="avatar">{currentUser.name.slice(0, 1)}</div><div><strong>{currentUser.name}</strong><small>{currentUser.role}</small></div></button><button className="logout" onClick={() => setShowLogoutConfirm(true)}>Sign out</button></div>
      </header>
      {showNotifications && <aside className="notifications"><div className="aside-title"><h3>Notifications</h3><button onClick={() => setShowNotifications(false)}>×</button></div>{notifications.length === 0 ? <p className="empty">Nothing new yet.</p> : notifications.map((item) => <div className={item.read ? 'notice read' : 'notice'} key={item.id}><strong>{item.title}</strong><p>{item.message}</p><div className="notice-channels">{(item.channels ?? ['in_app']).map((channel) => <span key={channel}>{notificationChannelLabel(channel)}</span>)}</div><small>{new Date(item.createdAt).toLocaleString()}</small></div>)}</aside>}
      <main className="dashboard">
        {error && <div className="error-banner dashboard-error">{error}</div>}

        {screen === 'overview' && <>
          <section className="welcome"><div><p className="eyebrow dark">{currentUser.role} workspace</p><h1>Good to see you, {currentUser.name.split(' ')[0]}.</h1><p>Here is what is happening with your work and payments.</p></div>{currentUser.role === 'freelancer' && <button className="primary" onClick={() => setShowCreate(true)}>+ New payment request</button>}</section>
          <section className="metrics">
            <div><small>Total requested</small><strong>{total.toLocaleString()} <em>BEAM</em></strong><span>Across {payments.length} request{payments.length === 1 ? '' : 's'}</span></div>
            <div><small>Protected in escrow</small><strong>{secured.toLocaleString()} <em>BEAM</em></strong><span className="positive">Funds secured</span></div>
            <div><small>{currentUser.role === 'freelancer' ? 'Total received' : 'Total released'}</small><strong>{paid.toLocaleString()} <em>BEAM</em></strong><span>Confirmed on chain</span></div>
            <div><small>Wallet connection</small><strong className="wallet-state"><i />{walletMode}</strong><span>{walletMode === 'mock' ? 'Local development mode' : 'Beam Wallet API'}</span></div>
          </section>
          <section className="analytics-strip">
            <div><small>Monthly revenue</small><strong>{monthlyRevenue.toLocaleString()} <em>BEAM</em></strong><span>Paid this month</span></div>
            <div><small>Active contracts</small><strong>{activeContracts}</strong><span>Counterparties with live work</span></div>
            <div><small>{analyticsLabel}</small><strong>{pendingSpend.toLocaleString()} <em>BEAM</em></strong><span>{analyticsHint}</span></div>
            <div><small>Attention needed</small><strong>{failedPayments + expiredPayments}</strong><span>{failedPayments} failed · {expiredPayments} expired</span></div>
          </section>
          <section className="section-heading"><div><h2>Payment activity</h2><p>Follow each request from approval to blockchain confirmation.</p></div><div className="heading-actions"><button className="secondary" onClick={() => void load()}>Refresh</button>{payments.length > 2 && <button className="secondary" onClick={() => setScreen('payments')}>View all</button>}</div></section>
          {paymentGrid(payments.slice(0, 4))}
        </>}

        {screen === 'payments' && <>
          <section className="screen-heading"><div><p className="eyebrow dark">Payment center</p><h1>Requests and escrow</h1><p>Manage approvals, delivery, disputes, and every on-chain confirmation.</p></div>{currentUser.role === 'freelancer' && <button className="primary" onClick={() => setShowCreate(true)}>+ New payment request</button>}</section>
          <section className="payment-overview">
            <div><span>All requests</span><strong>{payments.length}</strong></div>
            <div><span>Active</span><strong>{payments.filter((item) => !['released','disputed','failed','expired','cancelled'].includes(item.status)).length}</strong></div>
            <div><span>In escrow</span><strong>{secured.toLocaleString()} <small>BEAM</small></strong></div>
            <div><span>Completed</span><strong>{payments.filter((item) => item.status === 'released').length}</strong></div>
          </section>
          <section className="payments-toolbar">
            <div className="filter-tabs">{(['all','active','escrow','completed','disputed','failed','expired'] as PaymentFilter[]).map((filter) => <button key={filter} className={paymentFilter === filter ? 'active' : ''} onClick={() => setPaymentFilter(filter)}>{filter}</button>)}</div>
            <button className="secondary" onClick={() => void load()}>Refresh</button>
          </section>
          {paymentGrid(filteredPayments)}
        </>}

        {screen === 'wallet' && <>
          <section className="wallet-hero">
            <div><p className="eyebrow">Beam wallet</p><h1>Your private payment rail</h1><p>Escrow activity and blockchain confirmations connected to your WorkingBeam account.</p></div>
            <div className="connection-pill"><i />{walletMode === 'mock' ? 'Mock wallet connected' : 'Beam Wallet API connected'}</div>
          </section>
          <section className="wallet-layout">
            <div className="wallet-address-card">
              <div className="card-kicker">Receiving wallet</div>
              <h2>{currentUser.name}</h2>
              <p>Your freelancer releases and account transactions use this Beam address.</p>
              <div className="address-box"><code>{currentUser.walletAddress}</code><button onClick={() => void navigator.clipboard?.writeText(currentUser.walletAddress)}>Copy</button></div>
              <div className="wallet-badges"><span>{walletMode === 'mock' ? 'Privacy simulated in mock mode' : 'Private Beam transactions'}</span><span>{currentUser.emailVerified ? 'Email verified' : 'Email verification paused'}</span></div>
              <button className="secondary wallet-generate" disabled={busy === 'generate-wallet'} onClick={() => void generateWallet()}>{busy === 'generate-wallet' ? 'Generating...' : 'Generate wallet'}</button>
            </div>
            <div className="wallet-summary">
              <div><small>Protected now</small><strong>{secured.toLocaleString()} <em>BEAM</em></strong></div>
              <div><small>Confirmed volume</small><strong>{confirmedTransactions.reduce((sum, transaction) => sum + transaction.amountBeam, 0).toLocaleString()} <em>BEAM</em></strong></div>
              <div><small>Transactions</small><strong>{transactions.length}</strong></div>
            </div>
          </section>
          <section className="wallet-tools">
            <article>
              <div className="card-kicker">Deposit address</div>
              <h3>Receive BEAM</h3>
              <p>Share this address or token with a payer to receive funds into your WorkingBeam wallet profile.</p>
              <div className="address-box"><code>{currentUser.walletAddress}</code><button onClick={() => void navigator.clipboard?.writeText(currentUser.walletAddress)}>Copy</button></div>
            </article>
            <form className="send-payment-form" onSubmit={sendPayment}>
              <div><div className="card-kicker">Send payment</div><h3>Send BEAM</h3><p>Submit a direct wallet transfer outside an escrow request.</p></div>
              <label>Recipient address or token<input required minLength={10} value={sendForm.address} onChange={(event) => setSendForm({ ...sendForm, address: event.target.value })} placeholder="beam-recipient-wallet-address" /></label>
              <label>Amount (BEAM)<input required type="number" min="0.00000001" step="0.00000001" value={sendForm.amountBeam} onChange={(event) => setSendForm({ ...sendForm, amountBeam: event.target.value })} /></label>
              <label>Note <small>(optional)</small><input value={sendForm.note} onChange={(event) => setSendForm({ ...sendForm, note: event.target.value })} placeholder="Payment memo" /></label>
              <button className="primary full" disabled={busy === 'send-payment'}>{busy === 'send-payment' ? 'Sending...' : 'Send payment'}</button>
            </form>
          </section>
          <section className="section-heading wallet-section-heading"><div><h2>Transaction history</h2><p>Funding and release activity reported by the Beam wallet connection.</p></div><button className="secondary" onClick={() => void load()}>Refresh</button></section>
          <section className={`transaction-table ${transactions.length === 0 ? 'is-empty' : ''}`}>
            {transactions.length === 0 ? <div className="wallet-empty"><span>◇</span><h3>No wallet activity yet</h3><p>Transactions will appear after a client funds the first approved request.</p><button className="secondary" onClick={() => setScreen('payments')}>Go to payments</button></div> : <>{transactions.map((transaction) => <div className="transaction-row" key={transaction.id}><div className={`tx-icon ${transaction.kind}`}>{transaction.kind === 'funding' ? '↓' : '↑'}</div><div><strong>{transaction.paymentTitle}</strong><span>{transaction.kind === 'funding' ? 'Escrow funding' : 'Freelancer release'}</span></div><code>{transaction.walletTransactionId.slice(0, 20)}…</code><strong>{transaction.amountBeam.toLocaleString()} BEAM</strong><b className={transaction.status}>{transaction.status}</b></div>)}</>}
          </section>
          <section className="wallet-security"><div>✓</div><div><h3>Wallet security and privacy</h3><p>WorkingBeam never asks for your Beam seed phrase. Private transaction behavior is provided by the connected live Beam wallet; mock mode simulates the workflow without real privacy guarantees or real funds.</p></div></section>
        </>}

        {screen === 'transactions' && <>
          <section className="screen-heading"><div><p className="eyebrow dark">Transaction center</p><h1>Funding and release history</h1><p>Review every Beam transaction linked to your payment requests.</p></div><button className="secondary" onClick={() => void load()}>Refresh</button></section>
          <section className="payment-overview">
            <div><span>Total transactions</span><strong>{transactions.length}</strong></div>
            <div><span>Confirmed</span><strong>{confirmedTransactions.length}</strong></div>
            <div><span>Pending</span><strong>{transactions.filter((transaction) => transaction.status === 'pending').length}</strong></div>
            <div><span>Failed</span><strong>{transactions.filter((transaction) => transaction.status === 'failed').length}</strong></div>
          </section>
          <section className={`transaction-table ${transactions.length === 0 ? 'is-empty' : ''}`}>
            {transactions.length === 0 ? <div className="wallet-empty"><span>â—‡</span><h3>No transactions yet</h3><p>Funding and release transactions will appear after escrow activity begins.</p><button className="secondary" onClick={() => setScreen('payments')}>Go to payments</button></div> : transactions.map((transaction) => <div className="transaction-row" key={transaction.id}><div className={`tx-icon ${transaction.kind}`}>{transaction.kind === 'funding' ? 'â†“' : 'â†‘'}</div><div><strong>{transaction.paymentTitle}</strong><span>{transaction.kind === 'funding' ? 'Escrow funding' : transaction.kind === 'release' ? 'Freelancer release' : 'Refund'}</span></div><code>{transaction.walletTransactionId}</code><strong>{transaction.amountBeam.toLocaleString()} BEAM</strong><b className={transaction.status}>{transaction.status}</b></div>)}
          </section>
        </>}

        {screen === 'escrow' && <>
          <section className="screen-heading"><div><p className="eyebrow dark">Escrow overview</p><h1>Protected payments</h1><p>Track funds that are approved, pending confirmation, held, submitted, disputed, or ready for release.</p></div>{currentUser.role === 'freelancer' && <button className="primary" onClick={() => setShowCreate(true)}>+ New payment request</button>}</section>
          <section className="payment-overview">
            <div><span>Approved</span><strong>{payments.filter((item) => item.status === 'approved').length}</strong></div>
            <div><span>Funding pending</span><strong>{payments.filter((item) => item.status === 'funding_pending').length}</strong></div>
            <div><span>Held in escrow</span><strong>{secured.toLocaleString()} <small>BEAM</small></strong></div>
            <div><span>Disputed</span><strong>{payments.filter((item) => item.status === 'disputed').length}</strong></div>
          </section>
          {paymentGrid(payments.filter((payment) => ['approved','funding_pending','funded','work_submitted','release_pending','disputed'].includes(payment.status)))}
        </>}

        {screen === 'settings' && <>
          <section className="screen-heading"><div><p className="eyebrow dark">Workspace controls</p><h1>Settings</h1><p>Review account security, notification coverage, and operational safeguards.</p></div></section>
          <section className="settings-grid">
            <article><small>Authentication</small><strong>{currentUser.emailVerified ? 'Email verified' : 'Verification paused'}</strong><span>Sessions use hashed bearer tokens and server-side ownership checks.</span></article>
            <article><small>Email</small><strong>{emailAvailable ? emailMode : 'Needs setup'}</strong><span>{emailMode === 'smtp' ? 'Production SMTP health is checked by the API.' : 'Console/memory email is development-only; configure SMTP for production.'}</span></article>
            <article><small>Push notifications</small><strong>{pushAvailable ? pushMode : 'Needs setup'}</strong><span>{pushMode === 'webhook' ? 'Push webhook provider is configured.' : 'Payment events include push intent; configure a provider for device delivery.'}</span></article>
            <article><small>Push tokens</small><strong>{currentUser.pushTokens?.length ?? 0}</strong><span><button className="inline-action" disabled={busy === 'push-token'} onClick={() => void registerPushToken()}>{busy === 'push-token' ? 'Saving…' : 'Register device token'}</button></span></article>
            <article><small>SMS</small><strong>{smsAvailable ? smsMode : 'Needs setup'}</strong><span>{smsMode === 'webhook' ? 'SMS webhook provider is configured.' : 'Configure SMS webhook and phone numbers for text delivery.'}</span></article>
            <article><small>Notifications</small><strong>{notifications.length} events</strong><span>Payment, escrow, dispute, expiry, failure, delivery, and confirmation activity is tracked in-app.</span></article>
            <article><small>Wallet mode</small><strong>{walletMode}</strong><span>{walletMode === 'mock' ? 'Local mock wallet is active for development; private transactions are simulated.' : 'Live Beam Wallet API is connected for private Beam transactions.'}</span></article>
            <article><small>Security</small><strong>Server validated</strong><span>Actions are checked by role, ownership, wallet validation, and payment state.</span></article>
          </section>
        </>}

        {screen === 'outstanding' && <>
          <section className="screen-heading"><div><p className="eyebrow dark">Client dashboard</p><h1>Outstanding requests</h1><p>Requests that still need approval, funding, review, release, confirmation, or dispute attention.</p></div><button className="secondary" onClick={() => void load()}>Refresh</button></section>
          <section className="payment-overview">
            <div><span>Need approval</span><strong>{payments.filter((item) => item.status === 'pending').length}</strong></div>
            <div><span>Ready to fund</span><strong>{payments.filter((item) => item.status === 'approved').length}</strong></div>
            <div><span>Awaiting release</span><strong>{payments.filter((item) => item.status === 'work_submitted').length}</strong></div>
            <div><span>Disputed</span><strong>{payments.filter((item) => item.status === 'disputed').length}</strong></div>
          </section>
          {paymentGrid(outstandingPayments)}
        </>}

        {screen === 'history' && <>
          <section className="screen-heading"><div><p className="eyebrow dark">Client dashboard</p><h1>Payment history</h1><p>Completed requests and every payment request with recorded wallet activity.</p></div><button className="secondary" onClick={() => void load()}>Refresh</button></section>
          <section className="payment-overview">
            <div><span>History items</span><strong>{historyPayments.length}</strong></div>
            <div><span>Payments made</span><strong>{paid.toLocaleString()} <small>BEAM</small></strong></div>
            <div><span>Failed</span><strong>{failedPayments}</strong></div>
            <div><span>Expired</span><strong>{expiredPayments}</strong></div>
          </section>
          {paymentGrid(historyPayments)}
        </>}

        {screen === 'profile' && <>
          <section className="screen-heading"><div><p className="eyebrow dark">{currentUser.role === 'client' ? 'Client profile' : 'Freelancer profile'}</p><h1>Profile</h1><p>Review your account details. Use edit profile when you want to change your information.</p></div></section>
          <section className="profile-layout">
            {profileEditing ? <form className="profile-form" onSubmit={updateProfile}>
              <label>Full name<input required minLength={2} maxLength={80} value={profileForm.name} onChange={(event) => setProfileForm({ ...profileForm, name: event.target.value })} /></label>
              <label>Phone <small>(optional)</small><input maxLength={40} value={profileForm.phone} onChange={(event) => setProfileForm({ ...profileForm, phone: event.target.value })} placeholder="+211 ..." /></label>
              <label>Beam wallet address or token<input required minLength={10} value={profileForm.walletAddress} onChange={(event) => setProfileForm({ ...profileForm, walletAddress: event.target.value })} /></label>
              {error && <div className="error-banner">{error}</div>}
              <div className="profile-form-actions"><button type="button" className="secondary" disabled={busy === 'profile'} onClick={() => setProfileEditing(false)}>Cancel</button><button className="primary" disabled={busy === 'profile'}>{busy === 'profile' ? 'Saving...' : 'Save changes'}</button></div>
            </form> : <section className="profile-form profile-details"><div><small>Full name</small><strong>{currentUser.name}</strong></div><div><small>Email address</small><strong>{currentUser.email}</strong></div><div><small>Phone</small><strong>{currentUser.phone || 'Not provided'}</strong></div><div><small>Compliance</small><strong>{currentUser.complianceStatus ?? 'not_started'}</strong></div><div><small>Beam address or token</small><code>{currentUser.walletAddress}</code></div><button className="secondary profile-edit-button" disabled={busy === 'compliance'} onClick={() => void requestComplianceReview()}>{busy === 'compliance' ? 'Requesting…' : 'Request compliance review'}</button><button className="primary profile-edit-button" onClick={() => { setProfileForm({ name: currentUser.name, phone: currentUser.phone ?? '', walletAddress: currentUser.walletAddress }); setProfileEditing(true); }}>Edit profile</button></section>}
            <aside className="profile-summary"><div className="avatar">{currentUser.name.slice(0, 1)}</div><h2>{currentUser.name}</h2><p>{currentUser.email}</p><span>{currentUser.role}</span><span>{currentUser.emailVerified ? 'Email verified' : 'Email verification paused'}</span></aside>
          </section>
        </>}
      </main>
      {showLogoutConfirm && <div className="modal-backdrop" onMouseDown={() => setShowLogoutConfirm(false)}><section className="modal confirm-modal" role="dialog" aria-modal="true" aria-labelledby="signout-title" onMouseDown={(event) => event.stopPropagation()}><div className="confirm-icon">↗</div><h2 id="signout-title">Are you sure you want to sign out?</h2><p>Your current session will end. You can sign back in at any time.</p><div className="confirm-actions"><button className="secondary" onClick={() => setShowLogoutConfirm(false)}>Cancel</button><button className="signout-confirm" onClick={onLogout}>Sign out</button></div></section></div>}
      {showCreate && <div className="modal-backdrop" onMouseDown={() => setShowCreate(false)}><section className="modal" onMouseDown={(event) => event.stopPropagation()}><div className="aside-title"><div><p className="eyebrow dark">New request</p><h2>Request a payment</h2></div><button onClick={() => setShowCreate(false)}>×</button></div><form onSubmit={createPayment}><label>Client email<input type="email" required value={form.clientEmail} onChange={(e) => setForm({ ...form, clientEmail: e.target.value })} placeholder="client@example.com" /></label><label>Project or milestone<input required minLength={3} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Landing page design" /></label><label>Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="What is included in this payment?" /></label><div className="form-row three"><label>Amount<input type="number" required min="0.01" step="0.01" value={form.amountBeam} onChange={(e) => setForm({ ...form, amountBeam: e.target.value })} /></label><label>Currency<select required value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value as PaymentCurrency })}>{paymentCurrencies.map((currency) => <option key={currency} value={currency}>{currency}</option>)}</select></label><label>Due date<input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} /></label></div><button className="primary full" disabled={busy === 'create'}>{busy === 'create' ? 'Creating…' : 'Send payment request'}</button></form></section></div>}
    </div>
  );
}

function App() {
  const [token, setToken] = useState(() => localStorage.getItem('workingbeam_token') ?? '');
  const [user, setUser] = useState<User | null>(null);
  const [checking, setChecking] = useState(Boolean(token));
  const [route, setRoute] = useState(() => `${window.location.pathname}${window.location.search}`);

  useEffect(() => {
    const syncRoute = () => setRoute(`${window.location.pathname}${window.location.search}`);
    window.addEventListener('popstate', syncRoute);
    return () => window.removeEventListener('popstate', syncRoute);
  }, []);

  const navigate = useCallback((nextRoute: string) => {
    window.history.pushState({}, '', nextRoute);
    setRoute(nextRoute);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, []);

  useEffect(() => {
    if (!token) { setChecking(false); return; }
    request<{ user: User }>('/api/auth/me', token).then((result) => setUser(result.user)).catch(() => {
      localStorage.removeItem('workingbeam_token'); setToken('');
    }).finally(() => setChecking(false));
  }, [token]);

  const authenticated = (nextUser: User, nextToken: string) => {
    localStorage.setItem('workingbeam_token', nextToken); setUser(nextUser); setToken(nextToken);
    navigate(route.startsWith('/payment-requests/') ? route : '/app');
  };
  const logout = () => {
    void request('/api/auth/logout', token, { method: 'POST' }).catch(() => undefined);
    localStorage.removeItem('workingbeam_token'); setToken(''); setUser(null);
    navigate('/auth');
  };
  if (checking) return <div className="loading-screen"><div className="brand">Working<span>Beam</span></div><i /></div>;
  if (user && token) return <Dashboard initialUser={user} token={token} onLogout={logout} onUserUpdated={setUser} initialScreen={route.startsWith('/payment-requests/') ? 'payments' : 'overview'} />;
  const [publicPath, queryString = ''] = route.split('?');
  if (publicPath === '/auth' || publicPath.startsWith('/payment-requests/')) {
    return <AuthScreen onAuthenticated={authenticated} initialRegistering={new URLSearchParams(queryString).get('mode') === 'register'} />;
  }
  const knownPublicPaths: PublicPath[] = ['/', '/about', '/features', '/pricing', '/docs', '/contact'];
  return <PublicSite path={knownPublicPaths.includes(publicPath as PublicPath) ? publicPath as PublicPath : '/'} onNavigate={navigate} />;
}

export default App;

